# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-20 23:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11)),
                ('website', models.URLField()),
                ('location', models.CharField(max_length=30)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=6)),
                ('camera', models.CharField(choices=[('SONY', 'Sony'), ('NIKON', 'Nikon'), ('CANON', 'Canon'), ('FUJIFILM', 'Fujifilm')], default='CANON', max_length=4)),
                ('services', models.CharField(choices=[('FAMILY', 'Family'), ('BABIES', 'Babies'), ('WEDDINGS', 'Weddings'), ('SCHOOL', 'School'), ('OTHER', 'Other'), ('ABSTACT', 'Abstract'), ('NATURE', 'Nature')], default='OTHER', max_length=7)),
                ('bio', models.TextField()),
                ('photo_styles', models.CharField(choices=[('COLOR', 'Color'), ('BW', 'Black and white'), ('ACTION', 'Action'), ('STILL', 'Still')], default='COLOR', max_length=4)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
