# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-28 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagerprofile',
            name='first_name',
            field=models.CharField(default='First', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagerprofile',
            name='last_name',
            field=models.CharField(default='Last', max_length=30),
            preserve_default=False,
        ),
    ]
