# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-20 23:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagerprofile',
            name='camera',
            field=models.CharField(choices=[('CANON', 'Canon'), ('NIKON', 'Nikon'), ('SONY', 'Sony'), ('FUJIFILM', 'Fujifilm')], default='CANON', max_length=4),
        ),
        migrations.AlterField(
            model_name='imagerprofile',
            name='photo_styles',
            field=models.CharField(choices=[('BW', 'Black and white'), ('COLOR', 'Color'), ('STILL', 'Still'), ('ACTION', 'Action')], default='COLOR', max_length=4),
        ),
        migrations.AlterField(
            model_name='imagerprofile',
            name='services',
            field=models.CharField(choices=[('WEDDINGS', 'Weddings'), ('SCHOOL', 'School'), ('FAMILY', 'Family'), ('BABIES', 'Babies'), ('NATURE', 'Nature'), ('ABSTACT', 'Abstract'), ('OTHER', 'Other')], default='OTHER', max_length=7),
        ),
    ]
