# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-02 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_profile', '0002_auto_20171128_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagerprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='imagerprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='imagerprofile',
            name='location',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='imagerprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='imagerprofile',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
