# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-21 04:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('imager_profile', '0002_auto_20171120_2341'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='imagerprofile',
            managers=[
                ('active', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='imagerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
