# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 22:55
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('imager_profile', '0005_auto_20171121_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagerprofile',
            name='camera',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('CANON', 'Canon'), ('NIKON', 'Nikon'), ('SONY', 'Sony'), ('FUJIFILM', 'Fujifilm')], default='CANON', max_length=25),
        ),
        migrations.AlterField(
            model_name='imagerprofile',
            name='photo_styles',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('BW', 'Black and white'), ('COLOR', 'Color'), ('STILL', 'Still'), ('ACTION', 'Action')], default='COLOR', max_length=21),
        ),
        migrations.AlterField(
            model_name='imagerprofile',
            name='services',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('WEDDINGS', 'Weddings'), ('SCHOOL', 'School'), ('FAMILY', 'Family'), ('BABIES', 'Babies'), ('NATURE', 'Nature'), ('ABSTACT', 'Abstract'), ('OTHER', 'Other')], default='OTHER', max_length=50),
        ),
    ]
