# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_profile', '0008_imagerprofile_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='imagerprofile',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='imagerprofile',
            name='email',
        ),
        migrations.AlterField(
            model_name='imagerprofile',
            name='fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6),
        ),
    ]
