# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_profile', '0009_auto_20171127_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagerprofile',
            name='fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
