# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-29 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='docfile',
            field=models.ImageField(upload_to='images'),
        ),
    ]
