# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 00:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0002_auto_20171129_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='cover',
            field=models.ImageField(default='Screen_Shot_2017-09-18_at_8.36.51_PM.png', upload_to='cover-image'),
            preserve_default=False,
        ),
    ]
