# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 00:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0003_album_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='highlighted',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='photo',
            field=models.ManyToManyField(related_name='album', to='imager_images.Photo'),
        ),
    ]
